### DISCUSSION TITLE
BEGIN TF Docs comment is no comment when generating adoc

### DISCUSSION THREAD

**Discussion by SeameX** [terraform-docs/terraform-docs#588] [Q&A]
### Describe the bug
```
formatter: adoc

output:
  file: README.adoc
  mode: replace
```

Produces:
```
<!-- BEGIN_TF_DOCS -->
Content
<!-- END_TF_DOCS -->
```

The `<!-- -->` comment style does not exist in asciidoc so its interpreted as text which i dont want to see in my documentation. It would be awesome if you can change that to one of the following:
https://docs.asciidoctor.org/asciidoc/latest/comments/

### How can we reproduce it?
see above just generate tfdocs with format "adoc"

### Environment information
tfdocs 0.16
win11 -> wsl2 -> ubuntu -> tfdoc

I may be too dumb to use tfdocs but i guess its a small and easy to fix bug.

Best
SeameX

**Comment by khos2ow** [comment]
Sorry for the long delay.

Default template for generating content contains Markdown specific comment, as it is the most used format for terraform-docs, but you can provide your own template and more importantly your own [template comment](https://terraform-docs.io/user-guide/configuration/output/#template-comment).

To properly generating AsciiDoc format you can use:

```yaml
formatter: adoc

output:
  file: README.adoc
  mode: replace
  template: |-
    // BEGIN_TF_DOCS (or whatever else you want to word it here)
    {{ .Content }}
    // END_TF_DOCS (... also here)
```

**Comment by khos2ow** [comment]
Since this is not an actual bug, if you're ok with it, I'm going to convert this to discussion for visibility and future reference for other folks.

**Comment by davewongillies** [comment]
Is there any way to have no comment? I'm wanting to use this for json, but there are no comments in json

**Reply by davewongillies** [reply]
This doesn't work:

```
$ terraform-docs json . --output-template '{{ .Content }}'  --output-file output.json
Error: value of '--output-template' should contain at least 3 lines (begin comment, {{ .Content }}, and end comment)
```

Nor this:

```
$ terraform-docs json . --output-template '\n{{ .Content }}\n'  --output-file output.json
Error: value of '--output-template' is missing begin comment
```

**Reply by davewongillies** [reply]
Adding the `--output-mode replace` switch made it create a json file with no comment in it:

```
$ terraform-docs json . --output-mode replace  --output-template '{{ .Content }}'  --output-file output.json
```

**Reply by davewongillies** [reply]
So looks like this could've worked too (just realising I didn't read this thread properly:

```yaml
formatter: json

output:
  file: README.json
  mode: replace
  template: |-
    {{ .Content }}
```
