### DISCUSSION TITLE
Create README for terraform submodules

### DISCUSSION THREAD

**Discussion by mbarram** [terraform-docs/terraform-docs#747] [Q&A]
Hello, my organization uses the submodule approach for creating modules. We utilize GitHub Actions workflows to generate README files for each module. However, only the parent modules are currently documented. For instance, in the following example, a README is only created for the 'iam' module, not for its child modules.

modules
├── iam
│   ├── cloudfront-stack
│   ├── cloudwatch-rum-stack
│   ├── cognito-stack
│   ├── laravel-stack
│   ├── robot-stack
│   ├── s3-app
│   ├── serverless-stack

```
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: iac
        output-file: README.md
        output-method: inject
        git-push: "true"
        recursive: true
```

How can I create README files for the submodules as well?

Thank you!
