### ISSUE TITLE
Not getting the header-from to work.

### ISSUE THREAD

**Issue by jarnohenneman** [terraform-docs/terraform-docs#360]
It's probably me, but somehow the 'header-from' is not working.

Version.
terraform-docs version v0.10.1 2c91c55 windows/amd64 BuildDate: 2020-09-28T22:18:31+0000

.terraform-docs.yml
```
  formatter: markdown
  header-from: intro.md
  sections:
    hide-all: true
    show:
      - requirements
      - providers
      - inputs
      - outputs
  sort:
    enabled: true
    by:
      - required
  settings:
    indent: 2
    escape: false
```

intro.md
```
# Hello World
```

Command
`terraform-docs -c .terraform-docs.yml . > README.md`

The result in the README.md does contain the requirements, providers, etc. but not the intro.md.
