### ISSUE TITLE
New flag --header-from-mandatory

### ISSUE THREAD

**Issue by felipeneuwald** [terraform-docs/terraform-docs#389]
### What problem are you facing?

When `--header-from` is specified and no header file is found, terraform-docs fails: `Error: stat modules/my-module/.header.md: no such file or directory`; that's ok, that's the expected behavior as we can see [here](https://github.com/terraform-docs/terraform-docs/blob/master/internal/terraform/module.go#L188). 

But, when running [gh-actions](https://github.com/terraform-docs/gh-actions) with a configuration like the one below (`args: "--header-from .header.md"` and `find-dir: modules/`), it would be good to have an additional flag to continue terraform-docs execution even if no header file is found. 

```YAML
name: Generate terraform modules docs
on:
  push:
    branches:
      - main
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Render terraform docs and push changes to main branch
      uses: terraform-docs/gh-actions@v0.4.0
      with:
        args: "--header-from .header.md"
        find-dir: modules/
        output-file: README.md
        output-method: replace
        git-push: "true"
```

### How could terraform-docs help solve your problem?

1. add an additional bool flag `--header-from-mandatory`, default `true`;
2. add to func loadHeader: if file is not found && `!options.HeaderFromMandatory`, should return err nil. 

I didn't submit a PR yet because I'd like to check your thoughts first ;-)
