### ISSUE TITLE
I can't get the generated output to go to the destination file

### ISSUE THREAD

**Issue by evairmarinho** [terraform-docs/terraform-docs#439]
### Describe the bug
I'm trying to use the **terraform-docs** tool to generate a **markdown** for my .tf files. I managed to get the markdown return via **CLI**, but I couldn't get the **output** to go to any **file** of my preference.

### How can we reproduce it?
**Executed command**:

```sh
terraform-docs -c .terraform-docs.yml .
```

**Command output**:

```
## Requirements

No requirements.

## Providers

| Name | Version |
|------|---------|
| aws | n/a |

## Modules

No Modules.

## Resources

| Name |
|------|
| [aws_iam_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_group) |
| [aws_iam_user](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user) |
| [aws_iam_user_group_membership](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_user_group_membership) |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| region | Region where the resources will be created. | `string` | n/a | yes |
| access\_key | n/a | `string` | `""` | no |
| create\_groups | Define if Terraform will create new\_groups based on variable groups. | `bool` | `true` | no |
| groups | List of group names for Terraform create, case create\_groups variable be true | `list(string)` | `[]` | no |
| secret\_key | n/a | `string` | `""` | no |
| users | Map for Terraform create users. | `map(any)` | <pre>{<br>  "user1": {<br>    "groups": [<br>      "ADM",<br>      "developers"<br>    ],<br>    "name": "test",<br>    "path": "/"<br>  }<br>}</pre> | no |

## Outputs

No output.
```

### Environment information
**terraform-docs version** : 0.11.2 bd351fc windows/amd64 BuildDate: 2021-02-22T23:52:49Z
**OS**: Windows 
**File structure of directory**:

```
.
├── .terraform/
├── .terraform-docs.yml
├── .terraform.lock.hcl 
├── backend.tf 
├── env.tfvars 
├── examples/ 
├── main.tf 
├── README.md 
├── terraform.tfstate
├── terraform.tfstate.backup 
├── variables.tf
``` 
**.terraform-docs.yml file** :
``` yml
formatter: markdown
header-from: main.tf
footer-from: ""

sections:
  hide-all: false
  hide: []
  show-all: true
  show: []

output:
  file: teste.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by:
    - required

settings:
  anchor: true
  color: true
  default: true
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
```
