### ISSUE TITLE
Return name of file when using file output

### ISSUE THREAD

**Issue by rickhlx** [terraform-docs/terraform-docs#456]
### What problem are you facing?

Using GitLab CI to check if terraform docs are up to date. There is no way to know if running `terraform-docs` updated a file when run. 

Using `terraform fmt` as an example, we can easily check if a file changed and fail the pipeline if true. 

### How could terraform-docs help solve your problem?

When a file changed, returning the filename would allow us to know if a file changed and fail if true. Meaning the docs were not updated when the module changed.

**Comment by khos2ow** [comment]
I can see the benefit of showing changed file name only if `--output-file` is set., but regardless you can rely always on git, because at the end of the day terraform-docs needs to be run on CI for this validation:

- using `git status`

  ```yaml
  document:
    stage: validate
    script:
      - terraform-docs .
      - test -z "$(git status --porcelain)" || exit 1
  ```
- using `git diff`

  ```yaml
  document:
    stage: validate
    script:
      - terraform-docs .
      - git diff --exit-code
  ```

For example we use [similar approach](https://github.com/terraform-docs/terraform-docs/blob/master/.github/workflows/ci.yaml#L76) here to validate if documents are updated (if needed) as part of a PR. Or how it's being [used](https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L198-L203) in [gh-actions](https://github.com/terraform-docs/gh-actions).
