### ISSUE TITLE
Unable to decode config

### ISSUE THREAD

**Issue by thawkins83** [terraform-docs/terraform-docs#496]
### Describe the bug

With v0.13.0, I can no longer run `terraform-docs markdown table .` Get the following error:

```
Error: unable to decode config, 1 error(s) decoding:

* 'sort.by' expected type 'string', got unconvertible type '[]interface {}'
```
I have a Docker image that has v0.12.1 of terraform-docs & go1.1.5.10 and it still works from with that configuration.

### How can we reproduce it?

This is my `.terraform-docs.yml` file.
```
formatter: markdown table
header-from: header.md
footer-from: quick_start.md

sections:
  hide-all: false

output:
 file: README.md
 mode: replace
 template: |-
   <!-- BEGIN_TF_DOCS -->

   {{ .Content }}

   <!-- END_TF_DOCS -->

sort:
  enabled: true
  by:
    - required

settings:
  indent: 4
  escape: true
  default: true
  required: true
  type: true
```
### Environment information

```
$ terraform-docs -v
terraform-docs version v0.13.0 darwin/amd64 BuildDate: 2021-05-01T01:04:33+0100
$ go version
go version go1.16.3 darwin/amd64

```

**Comment by khos2ow** [comment]
The sort behavior was changed a bit in #467, and `sort.by` in configuration was converted to `string` as opposed to `list`. If you change your config to following it will work:

```yaml
...

sort:
  enabled: true
  by: required
```

Although this made me realize that [user guide](https://terraform-docs.io/user-guide/configuration/#sort) and corresponding [release note](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.13.0) (second item in `Breaking Changes`) are a bit misleading and don't reflect this specific change. I'll update them shortly.
