### ISSUE TITLE
sections.hide not working correctly

### ISSUE THREAD

**Issue by mengesb** [terraform-docs/terraform-docs#518]
### Describe the bug

Attempting to hide `resources` isn't working. It hides all but one, and generates a section of one resource. When no hide section is used, it generates my resources. The only way to get it to go away is to list all sections under `show` and remove the `hide` section.

All other sections hide correctly, resources is the only one performing incorrectly

### How can we reproduce it?

Config
```yml
# version: ""
formatter: markdown document
header-from: header.txt
# footer-from: ""

sections:
  hide:
      - resources
#   show:
#     - header
#     - requirements
#     - providers
#     - inputs
#     - outputs
#     - footer

# content: ""

# output:
#   file: ""
#   mode: inject
#   template: |-
#     <!-- BEGIN_TF_DOCS -->
#     {{ .Content }}
#     <!-- END_TF_DOCS -->

output-values:
  enabled: false

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  indent: 2
  required: true
  sensitive: true
  type: true
```

### Environment information

- terraform-docs version (use `terraform-docs --version`): `v0.14.1 darwin/amd64`
- OS (e.g. Windows, MacOS): MacOS

**Comment by khos2ow** [comment]
There are two types being shown in resources section, `resources` and `data-sources`. You can try this:

```yaml
sections:
  hide:
    - resources
    - data-sources
```

To completely hide all types of resources.
