### ISSUE TITLE
Pre-commit Docker in GitHub Actions generates faulty documentation for root module

### ISSUE THREAD

**Issue by petewilcock** [terraform-docs/terraform-docs#519]
### Describe the bug

Using pre-commit docker image as GitHub action has the very strange effect of pre-pending generated documentation with boilerplate from terraform-docs repo itself. 

Does not affect other hook calls to sub-modules in paths other than root directory. 

Also cannot reproduce locally (Ubuntu/WSL2) - works as expected there. 

![image](https://user-images.githubusercontent.com/6526265/120924743-09cda700-c6cd-11eb-90ae-d67a9cbbe29f.png)

### How can we reproduce it?
Pre-commit hook definition in `.pre-commit-config.yaml`
```
repos:
  - repo: local
    hooks:
      - id: terraform-docs-main
        name: terraform-docs-main
        language: docker_image
        entry: quay.io/terraform-docs/terraform-docs:latest
        args: ["--output-file", "README.md", "markdown", "."]
```
Calling pre-commit hook in GitHub action workflow via `pre-commit/action@v2.0.3`. 

Terraform docs config: `.terraform-docs.yml`

```
---
version: ""

formatter: <FORMATTER_NAME>

header-from: .header.md
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}
  {{ .Footer }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
```

### Environment information

GitHub action environment
```
jobs:
  pre-commit:
    runs-on: ubuntu-latest
```
Docker image: latest above is 0.14.1

Happy to provide additional info. Assuming there's something in the root of the workspace Docker is run in that's getting inadvertently picked up as a default?
