### ISSUE TITLE
BEGIN TF Docs comment is no comment when generating adoc

### ISSUE THREAD

**Issue by SeameX** [terraform-docs/terraform-docs#580]
### Describe the bug
```
formatter: adoc

output:
  file: README.adoc
  mode: replace
```

Produces:
```
<!-- BEGIN_TF_DOCS -->
Content
<!-- END_TF_DOCS -->
```

The "" comment style does not exist in asciidoc. It would be awesome if you can change that to one of the following:
https://docs.asciidoctor.org/asciidoc/latest/comments/

### How can we reproduce it?
see above just generate tfdocs with format "adoc"

### Environment information
tfdocs 0.16
win11 -> wsl2 -> ubuntu -> tfdoc

I may be too dumb to use tfdocs but i guess its a small and easy to fix bug.

Best
seamex

**Comment by khos2ow** [comment]
Sorry for the long delay.

Default template for generating content contains Markdown specific comment, as it is the most used format for terraform-docs, but you can provide your own template and more importantly your own [template comment](https://terraform-docs.io/user-guide/configuration/output/#template-comment).

To properly generating AsciiDoc format you can use:

```yaml
formatter: adoc

output:
  file: README.adoc
  mode: replace
  template: |-
    // BEGIN_TF_DOCS (or whatever else you want to word it here)
    {{ .Content }}
    // END_TF_DOCS (... also here)
```
