### ISSUE TITLE
Allow recursive path to include multiple sub paths 

### ISSUE THREAD

**Issue by kgopi1** [terraform-docs/terraform-docs#608]
### What problem are you facing?

Currently, the recursive path is searching only for the single path. We have a requirement to create docs files for multiple root directories. example:
I need to create a readme file for each environment file (dev, prod) under environments and create another readme file for each module. 

Currently, terraform-docs support only one recursive path. 

Can it be allowed to include both modules, and environments in the recursive path? 

### How could terraform-docs help solve your problem?

Allow the recursive path as a list instead of a string.

**Comment by Joerg-L** [comment]
We are facing nearly the same "issue" with our terraform configuration.
Our folder structure looks like this
```
├───modules
│   ├───container
│   │   ├───container_registry
│   │   └───k8s-cluster
│   ├───database
│   │   ├───mssql_database
│   │   ├───mssql_failovergroup
│   │   ├───mssql_full_ha_setup
│   │   ├───mssql_instance
│   │   ├───postgresql_flexinstance
│   │   └───postgresql_singleinstance
│   ├───keyvault
│   │   ├───azure_keyvault
│   │   ├───azure_keyvault_access_policy
│   │   ├───azure_keyvault_generate_key
│   │   └───azure_keyvault_generate_secret
│   ├───network
│   │   ├───peering
│   │   ├───spoke
│   │   │   └───example
│   │   ├───subnet
│   │   └───vnet
│   └───vm
│       ├───vmss_linux
│       ├───vm_linux
│       └───vm_windows
```
and it's still growing due to our journey with terraform has just started short time ago.

Workaround/different approch:
We know that another practise for Terraform Modules is, to put each module into it's own dedicated repository and switch the source attribute on the configuration pointing to git and not to local path

**Comment by Hidetoxin** [comment]
I'll will also like this functionality. I like how `infracost` manages this by creating an infracost.yml file indicating all the paths that needs to be referenced like the one below:

```yaml
version: 0.1

projects:
  - path: dev
    terraform_var_files:
      - dev.tfvars

  - path: dev
    terraform_var_files:
      - prod.tfvars
```
So maybe something like:

```yaml
---
version: "0.16"

modules:
  - path: "my/module/path/one"
    args:
    - "--lockfile"

  - path: "my/module/path/two"
    args:
    - "--lockfile"
     
````

More information can be found at: https://www.infracost.io/docs/features/config_file/
