### ISSUE TITLE
When using `recursive: true` allow skipping changes to root `README.md`

### ISSUE THREAD

**Issue by sysadmiral** [terraform-docs/terraform-docs#613]
### What problem are you facing?

When working in a repository used purely for modules it would be useful to be able to skip changes to the root `README.md`.

Since all of the modules are in subdirectories we only want to update the README in the subdirectory and not the root (which has no terraform code).

Currently when you run `terraform-docs` in recursive mode it generates the submodule docs correctly but also adds to the root README which makes no sense in this scenario.

### How could terraform-docs help solve your problem?

Possibly add `skip-root-readme` as an option:

```
recursive:
  enabled: true
  path: modules
  skip-root-readme: true
```

**Comment by aashery-square** [comment]
@blakegong any update on the fix?

**Comment by deeparavirdc** [comment]
Any update on this or a workaround to skip root README from being updated ?

**Comment by nosrio** [comment]
Hi! Any updates on this?

**Comment by ashleyghooper** [comment]
Could one of the project maintainers _please_ review @blakegong 's pull  request?

**Comment by armsnyder** [comment]
I'm working around this issue for now by using the `hide-empty` setting. It works as long as you don't have Terraform files in the root, and you're ok with hiding empty sections.

```yaml
output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
settings:
  hide-empty: true
```
