### ISSUE TITLE
sections.hide: ["all"] does not work on 0.16

### ISSUE THREAD

**Issue by shadycuz** [terraform-docs/terraform-docs#620]
### Describe the bug

terraform-docs creates all sections when it should not create any.

https://terraform-docs.io/user-guide/configuration/sections/

### How can we reproduce it?

Create an empty directory with this config:
```yml
formatter: "markdown"

output:
  file: README.md
  mode: inject

recursive:
  enabled: true

sections:
  hide:
    - all
```
run `terraform-docs .`

Get this output: 

```markdown
<!-- BEGIN_TF_DOCS -->
## Requirements

No requirements.

## Providers

No providers.

## Modules

No modules.

## Resources

No resources.

## Inputs

No inputs.

## Outputs

No outputs.
<!-- END_TF_DOCS -->
```

But I expected
```markdown
<!-- BEGIN_TF_DOCS -->
<!-- END_TF_DOCS -->
```

### Environment information

terraform-docs version v0.16.0 linux/amd64
