### ISSUE TITLE
output mode replace cannot be used when configured with pre-commit

### ISSUE THREAD

**Issue by timharsch** [terraform-docs/terraform-docs#633]
### Describe the bug
I have a config file at: .config/.terraform-docs.yaml
```yaml
formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # header...

  example project description

  {{ .Header }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Modules }}

  {{ .Outputs }}

  {{ .Requirements }}

  ## Resources
  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}
  {{ .Footer }}
  ## Notes

  notes

output:
  file: ""
  mode: replace
  template: |-
    {{ .Content }}

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

```

* .pre-commit-config.yaml
```
...
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.16.0
  hooks:
    - id: terraform-docs-go
      files: .config
      types: [yaml]
      args: ["markdown", "table", "--output-file", "README.md", "."]
```

If i do git commit and I have staged an update to my template in .config/.terraform-docs.yaml, then I always get the error:

```
terraform-docs...........................................................Failed
- hook id: terraform-docs-go
- files were modified by this hook
```
No matter if the content is exactly as it was before. I think since the replace operation generates a new file for README.md every time, and does not know that it is the exact same content, it trips the error.

My expectation is that if terraform-docs modifies the README.md, then I can stage the modified contents, run `git commit` and have it go through.

My workaround was to `git commit --no-verify` to force the commit through. So long as there are no changes to .config/.terraform-docs.yaml then the terraform-docs command does not run 🤷

### How can we reproduce it?

create a config file with 'output: mode: replace', make changes to your content section,
