### ISSUE TITLE
Hidden module section leaves empty lines

### ISSUE THREAD

**Issue by Matthijsy** [terraform-docs/terraform-docs#640]
### Describe the bug

When I use the sections `input`, `modules` and `outputs`, and the `modules` section is empty it still renders two empty lines. 

### How can we reproduce it?

Use this configuration:
```
formatter: "markdown table"

output:
  file: "README.md"
  mode: inject

sections:
  show:
    - inputs
    - modules
    - outputs

settings:
  anchor: false
  html: false
  hide-empty: true
```

It results in the following:

```
<!-- BEGIN_TF_DOCS -->


## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| input | input | `string` | `"Default"` | no |

## Outputs

| Name | Description |
|------|-------------|
| output | output |
<!-- END_TF_DOCS -->
```

The issue are the 2 blank lines after `BEGIN_TF_DOCS`

### Environment information

- `terraform-docs version v0.16.0 darwin/amd64`
- `MacOS`
