### ISSUE TITLE
Using YAML block multiline string for `output.template` results in `Error: value of '--output-template' is missing end comment`

### ISSUE THREAD

**Issue by ccampo133** [terraform-docs/terraform-docs#652]
### Describe the bug

Specifying the `output.template` value as a YAML multiline block in `.terraform-docs.yml` string results in the error `Error: value of '--output-template' is missing end comment`, despite the end comment clearly existing.

If you specify as a regular quoted string with linebreaks, it works as expected (no error).

### How can we reproduce it?

Pretty simple to reproduce. Create the following files:

`main.tf`:
```hcl
/**
 * Hello world!
 */
resource "null_resource" "foo" {}
```

`.terraform-docs.yml`:

```yaml
formatter: "markdown"

output:
  file: "README.example.md"
  mode: inject
  # Using a block style string does not appear to work...
  #... however a string with linebreaks does (uncomment to test, and comment 
  # out the block template).
  #template: "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->  
```

And you'll see the following error:
```
$ terraform-docs .
Error: value of '--output-template' is missing end comment
```

See my example repo: https://github.com/ccampo133/terraform-docs-template-comment-bug

### Environment information

terraform-docs version v0.16.0 darwin/amd64
MacOS Monterey 12.6

**Comment by ccq1994** [comment]
@ccampo133 I found the issue - the docs' example code has trailing spaces following `<!-- END_TF_DOCS -->`.  I'll open a PR.

**Comment by ccq1994** [comment]
Upon further inspection, it's not a fault in the documentation as it's written.  It's an issue with how the code blocks are rendered on terraform-docs.io.  If you copy the contents from the site, it includes a lot of trailing spaces:
<img width="254" alt="image" src="https://user-images.githubusercontent.com/44987790/206543312-93406b52-4e7d-40ca-a932-bd0863ef61bc.png">

However, [the code itself](https://github.com/terraform-docs/terraform-docs/blob/master/docs/user-guide/configuration.md?plain=1#L98) doesn't actually have trailing spaces.

This has to do with how the site is rendered and I have no clue how to work with that.  Hopefully this helps people figure out this problem, at least.

**Comment by ccampo133** [comment]
@ccq1994 confirmed that removing the trailing spaces does appear to resolve the issue I reported. I think it would make sense to have the code ignore/trim any whitespace following the comment.

**Comment by ccampo133** [comment]
I opened a PR for this here: https://github.com/terraform-docs/terraform-docs/pull/658

**Comment by nikolaik** [comment]
If you intent to write a newline after `<!-- END_TF_DOCS -->` i.e. the template `<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->\n` will the fix in #658 still work?

If the newline is missing, this is something that git clients will tell you about, like explained here: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

**Comment by ccampo133** [comment]
@nikolaik yes, although I'm not sure that your question is relevant to this issue. The template in question here must be passed in the YAML file, under the `output.template` key - it cannot live in its own file. You can have an arbitrary amount of newlines at the end of the template block and this will work, and so far as I can tell, this has always worked, for example:

`.terraform-docs.yaml`:
```yaml
formatter: "markdown"

output:
  file: "README.example.md"
  # Using a block style string does not appear to work...
  #... however a string with linebreaks does (uncomment to test, and comment
  # out the block template).
  #template: "<!-- BEGIN_TF_DOCS -->\n{{ .Content }}\n<!-- END_TF_DOCS -->"
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

  mode: inject
```
