### ISSUE TITLE
Markdown not rendering on section headings.

### ISSUE THREAD

**Issue by NiallJude** [terraform-docs/terraform-docs#671]
### Describe the bug

I am running into an issue wherein section headings are not rendering correctly on Bitbucket without manual editing. And every time I run `terraform-docs` again it overwrites my manual headers back to non-rendering headers.

Essentially I expect to have Heading register using the standard Markdown shortcut "## Heading" but instead, without intervention this is rendering literally.

Not Working (terraform-docs):
![image](https://user-images.githubusercontent.com/30654767/221883620-23b73468-b9c4-45c3-b655-0409a9d21998.png)

Working:
![image](https://user-images.githubusercontent.com/30654767/221883533-51f8ed99-7b96-4ab1-92e9-c3361dac8ac7.png)

I believe it is not working because codewise the generated code starts a new section directly under the previous block, instead of including a line of whitespace as below:
![image](https://user-images.githubusercontent.com/30654767/221883918-762b0212-1fda-48ba-94d8-1b8007bda35c.png)

Is there a way to make this whitespace between sections explicit so that the Markdown processes correctly? Or am I doing something wrong?

My config file:

```
formatter: "markdown table" # this is required
version: "0.16"
header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: ""

sections:
  hide: []
  show:
    - all

content: |-
  {{ .Header }}
  {{ .Footer }}
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Modules }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}


output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_TF_DOCS -->
      {{ .Content }}
      <!-- END_TF_DOCS -->

output-values:
  enabled: true
  from: "./output_values.json"

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
  ```

### How can we reproduce it?

Run terraform-docs on a given workspace. Are there whitespace lines between headings to allow Markdown to process?

### Environment information
terraform-docs version v0.16.0 darwin/arm64
MacOS.
