### ISSUE TITLE
pre-commit hook doesn't generate docs

### ISSUE THREAD

**Issue by poparotsy** [terraform-docs/terraform-docs#684]
### Describe the bug

pre-commit run terraform-docs-go OR terraform-docs-system,  doesn't generate docs file no matter what is the output-file nor module path is.

`.pre-commit-config.yaml`
```yaml
- repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      # - id: terraform-docs-go
      - id: terraform-docs-system
        args: ["markdown", "table", "--output-file", "../../docs/terraform-docs-test.md", "./infra/tf"]

```

Running 
```bash
pre-commit run terraform-docs-go
# OR
pre-commit run terraform-docs-system

# Always get skipped
# terraform-docs.......................................(no files to check)Skipped
# - hook id: terraform-docs-system
```

### The expected behaviour
pre-commit hook should work the same as the command line works.

e.g. terrafrom-docs command with the same arguments as the YAML file 
```bash
terraform-docs markdown table --output-file ../../docs/terraform-docs-test.md ./infra/tf
# docs/terraform-docs-test.md updated successfully
```

### Note:
--output-file $PATH must be relative to terraform-module-path which is weird!... it should've been wherever specified.

### How can we reproduce it?

- Use similar configuration as the above .pre-commit-config.yaml. 
- `pre-commit run terraform-docs-go` OR `terraform-docs-system`

### Environment information

- terraform-docs version v0.16.0 darwin/arm64
- MacOS
