### ISSUE TITLE
Allow Variables in Source Fields

### ISSUE THREAD

**Issue by coreyd-valcre** [terraform-docs/terraform-docs#793]
### What problem are you facing?

`Error: Variables not allowed: Variables may not be used here. (and 87 other messages)`

That is an error that comes up now, this is specific for the location of parent modules when using a variable in the source field. This is a change with OpenTofu 1.8.0 where we are able to utilize variables in the source at this point in time, such as for target branches.

### How could terraform-docs help solve your problem?

Allowing this feature would enhance the use for the community as a whole who uses both TF and Open TOFU. This would allow creation of docs without error when a variable is used in a place like the `source` item where Terraform does not allow it. It could be a simple `if` statement to check against it. The result of the variable does not initially need to be populated, it could very easily be left as is in the code.

**Comment by Shr3ps** [comment]
Need this too :)

**Comment by skyzyx** [comment]
Does anyone have some Terraform code that can be used for a test while fixing this?

**Comment by jessefarinacci** [comment]
I thought OP might post a config, but here is one that demonstrates two core issues for me w/r/t variables and standard stuff that OpenTofu allows in HCL.

```yaml
# .terraform-docs.yaml
formatter: "markdown document"
output:
  file: "README.md"
  mode: "replace"
  template: |-
    {{ .Content }}
recursive:
  enabled: true
sections:
  show:
    - all
settings:
  anchor: false
  hide-empty: true
  html: false
  read-comments: false
```

```hcl
# bugged.tf
variable "s3-bucket" {
  default = "my-bucket-name"
  type    = string
}

variable "s3-region" {
  default = "us-east-1"
  type    = string
}

module "bugged1" {
  source = format("s3::https://%s.s3.%s.amazonaws.com/modules/bug/module.zip", var.s3-bucket, var.s3-region)
}

module "bugged2" {
  source = "s3::https://${var.s3-bucket}.s3.${var.s3-region}.amazonaws.com/modules/bug/module.zip"
}
```

```console
❯ terraform-docs .
bugged1: Error: Function calls not allowed: Functions may not be called here. (and 31 other messages)
bugged2: Error: Variables not allowed: Variables may not be used here. (and 33 other messages)

❯ terraform-docs --version
terraform-docs version v0.24.0 darwin/arm64
```
