### ISSUE TITLE
Wrong exit code for pre-commit hooks

### ISSUE THREAD

**Issue by LukaK** [terraform-docs/terraform-docs#795]
### Describe the bug

Hi this issue is related to already reported issue [link](https://github.com/terraform-docs/terraform-docs/issues/719)  but I would suggest failing the hook instead of auto adding the changes similar to tools like `black`.

When you run `pre-commit run --all-files` or change moduel files, hook passes even if it updates the documentation leading to incomplete commits and hacks like the one below. Disabling `fail_fast` and adding additional step to check the documentation before updating it.

```yaml
default_stages:
  - pre-commit
  - pre-push

fail_fast: false

repos:

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:

      - id: terraform-docs-go
        name: terraform-docs-check
        args: ["--recursive", "--recursive-path", "modules", "--recursive-include-main=false", "--output-file", "README.md", "markdown", "--output-check",  "./infrastructure"]

      - id: terraform-docs-go
        name: terraform-docs-generate
        args: ["--recursive", "--recursive-path", "modules", "--recursive-include-main=false", "--output-file", "README.md", "markdown",  "./infrastructure"]

```

### How can we reproduce it?

Create directory structure.
```bash
infrastructure/modules/test-module/main.tf
```
`main.tf`
```terraform
terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.62.0"
    }
  }
}

variable "env" {
  type        = string
  description = "Environment values"
}

resource "aws_s3_bucket" "this" {
  tags = {
    Name        = "${var.env}-mybucket"
    Environment = var.env
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  bucket = aws_s3_bucket.this.id

  block_public_acls       = true
  ignore_public_acls      = true
  restrict_public_buckets = true
  block_public_policy     = true

}

resource "aws_s3_bucket_server_side_encryption_configuration" "this2" {
  bucket = aws_s3_bucket.this.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}


output "bucket_name2" {
  value       = aws_s3_bucket.this.id
  description = "Bucket name"
}
```

`.pre-commit-config.yaml`
```yaml
default_stages:
  - pre-commit
  - pre-push

fail_fast: false

repos:

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.18.0"
    hooks:

      # - id: terraform-docs-go
      #   name: terraform-docs-check
      #   args: ["--recursive", "--recursive-path", "modules", "--recursive-include-main=false", "--output-file", "README.md", "markdown", "--output-check",  "./infrastructure"]

      - id: terraform-docs-go
        name: terraform-docs-generate
        args: ["--recursive", "--recursive-path", "modules", "--recursive-include-main=false", "--output-file", "README.md", "markdown",  "./infrastructure"]

```
