### ISSUE TITLE
terraform-docs pre-commit hooks doesn't generate README file

### ISSUE THREAD

**Issue by mcinquin** [terraform-docs/terraform-docs#836]
### Describe the bug

Hello,

I have an issue with terraform-docs pre-commit hooks.
It never updates README file.

```
# pre-commit run -avvvvvv
trim trailing whitespace.................................................Passed
- hook id: trailing-whitespace
- duration: 0.07s
fix end of files.........................................................Passed
- hook id: end-of-file-fixer
- duration: 0.07s
Terraform fmt........................................(no files to check)Skipped
- hook id: terraform_fmt
Terraform validate with tflint.......................(no files to check)Skipped
- hook id: terraform_tflint
terraform-docs.......................................(no files to check)Skipped
```

But when I manually run terraform-docs, it works
```
# terraform-docs blueprint/ -c .terraform-docs.yml
README.md updated successfully

# git status
git status
On branch terraform-docs
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   blueprint/main.tf
	new file:   blueprint/versions.tf

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md
```

### How can we reproduce it?
See above

### Environment information

- terraform-docs version (use `terraform-docs --version`): 1.9.0
- OS (e.g. Windows, MacOS): Ubuntu
- folder
<details>

```
.
├── blueprint
│   ├── main.tf
│   └── versions.tf
├── bubu
├── CHANGELOG.md
├── Dockerfile-semantic-release
├── .git
├── .gitlab-ci.yml
├── Makefile
├── .pre-commit-config.yaml
├── README.md
├── .releaserc.yml
├── renovate.json
├── tata
├── .terraform-docs.yml
├── tete
├── titi
├── toto
├── tutu
└── tyty
```
</details>

- terraform-docs.yml

<details>

```
formatter: markdown table

sections:
  hide-all: true

content: |-
  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ../README.md
  mode: inject
  template: |-
    <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->

    {{ .Content }}

    <!-- END_AUTOMATED_TF_DOCS_BLOCK -->

output-values:
  enabled: false
  from: "outputs.tf"

sort:
  enabled: true
  by: "required"

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 3
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
```
</details>

- pre-commit-config.yaml

<details>

```
default_stages: [pre-commit]
repos:
    - repo: https://github.com/terraform-docs/terraform-docs
      rev: "v0.19.0"
      hooks:
        - id: terraform-docs-system
          args: ["-c", ".terraform-docs.yml", "./blueprint"]
```
</details>
